"""empty message

Revision ID: 3d01bb6136ec
Revises: 733221d928f9
Create Date: 2021-05-18 10:58:53.334167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d01bb6136ec'
down_revision = '733221d928f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_school_list_id', table_name='school_list')
    op.drop_table('school_list')
    op.drop_index('ix_district_id', table_name='district')
    op.drop_table('district')
    op.drop_index('ix_region_id', table_name='region')
    op.drop_table('region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('district_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='district_region_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='district_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_district_id', 'district', ['id'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('region_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='region_pkey'),
    sa.UniqueConstraint('name', name='region_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_region_id', 'region', ['id'], unique=False)
    op.create_table('school_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name='school_list_district_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='school_list_pkey')
    )
    op.create_index('ix_school_list_id', 'school_list', ['id'], unique=False)
    # ### end Alembic commands ###
