"""empty message

Revision ID: bd346a784257
Revises: 
Create Date: 2021-05-18 04:24:29.013051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd346a784257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_school_list_id', table_name='school_list')
    # op.drop_index('ix_region_id', table_name='region')
    # op.drop_table('region')
    # op.drop_index('ix_district_id', table_name='district')
    # op.drop_table('district')
    # op.drop_table('school_list')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('school_list',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='school_list_district_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='school_list_pkey')
    # )
    # op.create_index('ix_school_list_id', 'school_list', ['id'], unique=False)
    # op.create_table('regions',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='regions_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('ix_regions_id', 'regions', ['id'], unique=False)
    # op.create_table('districts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='districts_region_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='districts_pkey')
    # )
    # op.create_index('ix_districts_id', 'districts', ['id'], unique=False)
    pass
    # ### end Alembic commands ###
