"""empty message

Revision ID: c2364f3981bc
Revises: 3d01bb6136ec
Create Date: 2021-06-07 13:17:10.187174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2364f3981bc'
down_revision = '3d01bb6136ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
