"""empty message

Revision ID: 1c4fbb38c615
Revises: bd346a784257
Create Date: 2021-05-18 10:25:49.971626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c4fbb38c615'
down_revision = 'bd346a784257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_school_list_id', table_name='school_list')
    op.drop_table('school_list')
    op.drop_index('ix_districts_id', table_name='districts')
    op.drop_table('districts')
    op.drop_index('ix_regions_id', table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name='school_list_district_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='school_list_pkey')
    )
    op.create_index('ix_school_list_id', 'school_list', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='regions_pkey'),
    sa.UniqueConstraint('name', name='regions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_regions_id', 'regions', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='districts_region_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='districts_pkey')
    )
    op.create_index('ix_districts_id', 'districts', ['id'], unique=False)
    # ### end Alembic commands ###
