"""empty message

Revision ID: 733221d928f9
Revises: 1c4fbb38c615
Create Date: 2021-05-18 10:32:27.839704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733221d928f9'
down_revision = '1c4fbb38c615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
